name:                haskell-pkcs
version:             0.1.0.0
github:              "githubuser/haskell-pkcs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-pkcs#readme>

dependencies:
- base >= 4.9 && <4.11
- hspkcs11 >= 0.7
- bytestring >= 0.10.8.2
- base64-bytestring >= 1.0.0.2
- blake2 >= 0.2.0
- base58-bytestring >= 0.1.0
- hex >= 0.1.2
- servant >= 0.14.1
- servant-server >= 0.14.1
- warp
- wai
- yaml
- containers
- convertible
- aeson
- unix

library:
  source-dirs: src

executables:
  haskell-pkcs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-pkcs

tests:
  haskell-pkcs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-pkcs
