name:                hsm-signer
version:             0.1.0.0
github:              "github.com/throughnothing/hsm-signer"
license:             BSD3
author:              "William Wolf"
maintainer:          "throughnothing@gmail.com"
copyright:           "2018 William Wolf"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/throughnothing/hsm-signer#readme>

dependencies:
- base >= 4.9 && <4.11
- hspkcs11 >= 0.7
- bytestring >= 0.10.8.2
- base64-bytestring >= 1.0.0.1
- base58-bytestring >= 0.1.0
- servant >= 0.14.1
- servant-server >= 0.14.1
- warp
- wai
- yaml
- aeson
- unix
- cryptonite
- pem
- asn1-encoding
- asn1-types
- largeword
- memory

library:
  source-dirs: src

executables:
  server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-pkcs

tests:
  haskell-pkcs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-pkcs
